hc/front/urls.py
from django.conf.urls import include, url

from hc.front import views

check_urls = [
    url(r'^name/$', views.update_name, name="hc-update-name"),
    url(r'^timeout/$', views.update_timeout, name="hc-update-timeout"),
    url(r'^pause/$', views.pause, name="hc-pause"),
    url(r'^remove/$', views.remove_check, name="hc-remove-check"),
    url(r'^log/$', views.log, name="hc-log"),
    url(r'^last_ping/$', views.last_ping, name="hc-last-ping"),
]

channel_urls = [
    url(r'^$', views.channels, name="hc-channels"),
    url(r'^add_email/$', views.add_email, name="hc-add-email"),
    url(r'^add_webhook/$', views.add_webhook, name="hc-add-webhook"),
    url(r'^add_pd/$', views.add_pd, name="hc-add-pd"),
    url(r'^add_slack/$', views.add_slack, name="hc-add-slack"),
    url(r'^add_slack_btn/$', views.add_slack_btn, name="hc-add-slack-btn"),
    url(r'^add_hipchat/$', views.add_hipchat, name="hc-add-hipchat"),
    url(r'^add_pushbullet/$', views.add_pushbullet, name="hc-add-pushbullet"),
    url(r'^add_discord/$', views.add_discord, name="hc-add-discord"),
    url(r'^add_pushover/$', views.add_pushover, name="hc-add-pushover"),
    url(r'^add_opsgenie/$', views.add_opsgenie, name="hc-add-opsgenie"),
    url(r'^add_victorops/$', views.add_victorops, name="hc-add-victorops"),
    url(r'^telegram/bot/$', views.telegram_bot),
    url(r'^add_telegram/$', views.add_telegram, name="hc-add-telegram"),
    url(r'^add_sms/$', views.add_sms, name="hc-add-sms"),
    url(r'^([\w-]+)/checks/$', views.channel_checks, name="hc-channel-checks"),
    url(r'^([\w-]+)/remove/$', views.remove_channel, name="hc-remove-channel"),
    url(r'^([\w-]+)/verify/([\w-]+)/$', views.verify_email,
        name="hc-verify-email"),
    url(r'^([\w-]+)/unsub/([\w-]+)/$', views.unsubscribe_email,
        name="hc-unsubscribe-alerts"),
]

urlpatterns = [
    url(r'^$', views.index, name="hc-index"),
    url(r'^checks/$', views.my_checks, name="hc-checks"),
    url(r'^checks/add/$', views.add_check, name="hc-add-check"),
    url(r'^checks/cron_preview/$', views.cron_preview),
    url(r'^checks/([\w-]+)/', include(check_urls)),
    url(r'^integrations/', include(channel_urls)),

    url(r'^docs/$', views.docs, name="hc-docs"),
    url(r'^docs/api/$', views.docs_api, name="hc-docs-api"),
    url(r'^docs/cron/$', views.docs_cron, name="hc-docs-cron"),
    url(r'^about/$', views.about, name="hc-about"),
    url(r'^privacy/$', views.privacy, name="hc-privacy"),
    url(r'^terms/$', views.terms, name="hc-terms"),
]

hc/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from hc.accounts.views import login as hc_login

urlpatterns = [
    url(r'^admin/login/', hc_login, {"show_password": True}),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('hc.accounts.urls')),
    url(r'^', include('hc.api.urls')),
    url(r'^', include('hc.front.urls')),
    url(r'^', include('hc.payments.urls'))
]

hc/api/models.py
# coding: utf-8

import hashlib
import json
import uuid
from datetime import datetime, timedelta as td

from croniter import croniter
from django.conf import settings
from django.core.checks import Warning
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from hc.api import transports
from hc.lib import emails

STATUSES = (
    ("up", "Up"),
    ("down", "Down"),
    ("new", "New"),
    ("paused", "Paused")
)
DEFAULT_TIMEOUT = td(days=1)
DEFAULT_GRACE = td(hours=1)
CHECK_KINDS = (("simple", "Simple"),
               ("cron", "Cron"))

CHANNEL_KINDS = (("email", "Email"),
                 ("webhook", "Webhook"),
                 ("hipchat", "HipChat"),
                 ("slack", "Slack"),
                 ("pd", "PagerDuty"),
                 ("po", "Pushover"),
                 ("pushbullet", "Pushbullet"),
                 ("opsgenie", "OpsGenie"),
                 ("victorops", "VictorOps"),
                 ("discord", "Discord"),
                 ("telegram", "Telegram"),
                 ("sms", "SMS"))

PO_PRIORITIES = {
    -2: "lowest",
    -1: "low",
    0: "normal",
    1: "high",
    2: "emergency"
}


def isostring(dt):
    """Convert the datetime to ISO 8601 format with no microseconds. """
    return dt.replace(microsecond=0).isoformat()


class Check(models.Model):

    class Meta:
        # sendalerts command will query using these
        index_together = ["status", "user", "alert_after"]

    name = models.CharField(max_length=100, blank=True)
    tags = models.CharField(max_length=500, blank=True)
    code = models.UUIDField(default=uuid.uuid4, editable=False, db_index=True)
    user = models.ForeignKey(User, models.CASCADE, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    kind = models.CharField(max_length=10, default="simple",
                            choices=CHECK_KINDS)
    timeout = models.DurationField(default=DEFAULT_TIMEOUT)
    grace = models.DurationField(default=DEFAULT_GRACE)
    schedule = models.CharField(max_length=100, default="* * * * *")
    tz = models.CharField(max_length=36, default="UTC")
    n_pings = models.IntegerField(default=0)
    last_ping = models.DateTimeField(null=True, blank=True)
    last_ping_body = models.CharField(max_length=10000, blank=True)
    alert_after = models.DateTimeField(null=True, blank=True, editable=False)
    status = models.CharField(max_length=6, choices=STATUSES, default="new")

    def name_then_code(self):
        if self.name:
            return self.name

        return str(self.code)

    def url(self):
        return settings.PING_ENDPOINT + str(self.code)

    def log_url(self):
        return settings.SITE_ROOT + reverse("hc-log", args=[self.code])

    def email(self):
        return "%s@%s" % (self.code, settings.PING_EMAIL_DOMAIN)

    def send_alert(self):
        if self.status not in ("up", "down"):
            raise NotImplementedError("Unexpected status: %s" % self.status)

        errors = []
        for channel in self.channel_set.all():
            error = channel.notify(self)
            if error not in ("", "no-op"):
                errors.append((channel, error))

        return errors

    def get_grace_start(self):
        """ Return the datetime when grace period starts. """

        # The common case, grace starts after timeout
        if self.kind == "simple":
            return self.last_ping + self.timeout

        # The complex case, next ping is expected based on cron schedule
        with timezone.override(self.tz):
            last_naive = timezone.make_naive(self.last_ping)
            it = croniter(self.schedule, last_naive)
            next_naive = it.get_next(datetime)
            return timezone.make_aware(next_naive, is_dst=False)

    def get_status(self, now=None):
        """ Return "up" if the check is up or in grace, otherwise "down". """

        if self.status in ("new", "paused"):
            return self.status

        if now is None:
            now = timezone.now()

        return "up" if self.get_grace_start() + self.grace > now else "down"

    def get_alert_after(self):
        """ Return the datetime when check potentially goes down. """

        return self.get_grace_start() + self.grace

    def in_grace_period(self):
        """ Return True if check is currently in grace period. """

        if self.status in ("new", "paused"):
            return False

        grace_start = self.get_grace_start()
        grace_end = grace_start + self.grace
        return grace_start < timezone.now() < grace_end

    def assign_all_channels(self):
        if self.user:
            channels = Channel.objects.filter(user=self.user)
            self.channel_set.add(*channels)

    def tags_list(self):
        return [t.strip() for t in self.tags.split(" ") if t.strip()]

    def to_dict(self):
        update_rel_url = reverse("hc-api-update", args=[self.code])
        pause_rel_url = reverse("hc-api-pause", args=[self.code])

        result = {
            "name": self.name,
            "ping_url": self.url(),
            "update_url": settings.SITE_ROOT + update_rel_url,
            "pause_url": settings.SITE_ROOT + pause_rel_url,
            "tags": self.tags,
            "grace": int(self.grace.total_seconds()),
            "n_pings": self.n_pings,
            "status": self.get_status()
        }

        if self.kind == "simple":
            result["timeout"] = int(self.timeout.total_seconds())
        elif self.kind == "cron":
            result["schedule"] = self.schedule
            result["tz"] = self.tz

        if self.last_ping:
            result["last_ping"] = isostring(self.last_ping)
            result["next_ping"] = isostring(self.get_grace_start())
        else:
            result["last_ping"] = None
            result["next_ping"] = None

        return result

    def has_confirmation_link(self):
        return "confirm" in self.last_ping_body.lower()

    @classmethod
    def check(cls, **kwargs):
        errors = super(Check, cls).check(**kwargs)

        trigger_detected = False
        try:
            dummy = Check(last_ping=timezone.now())
            dummy.save()
            dummy.refresh_from_db()
            trigger_detected = bool(dummy.alert_after)
            dummy.delete()
        except:
            pass

        if trigger_detected:
            err = Warning(
                "Obsolete 'update_alert_after' trigger exists in database.",
                hint="Please remove the trigger with 'manage.py droptriggers'",
                id="hc.api.E001")
            errors.append(err)

        return errors


class Ping(models.Model):
    n = models.IntegerField(null=True)
    owner = models.ForeignKey(Check, models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    scheme = models.CharField(max_length=10, default="http")
    remote_addr = models.GenericIPAddressField(blank=True, null=True)
    method = models.CharField(max_length=10, blank=True)
    ua = models.CharField(max_length=200, blank=True)


class Channel(models.Model):
    code = models.UUIDField(default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    kind = models.CharField(max_length=20, choices=CHANNEL_KINDS)
    value = models.TextField(blank=True)
    email_verified = models.BooleanField(default=False)
    checks = models.ManyToManyField(Check)

    def assign_all_checks(self):
        checks = Check.objects.filter(user=self.user)
        self.checks.add(*checks)

    def make_token(self):
        seed = "%s%s" % (self.code, settings.SECRET_KEY)
        seed = seed.encode("utf8")
        return hashlib.sha1(seed).hexdigest()

    def send_verify_link(self):
        args = [self.code, self.make_token()]
        verify_link = reverse("hc-verify-email", args=args)
        verify_link = settings.SITE_ROOT + verify_link
        emails.verify_email(self.value, {"verify_link": verify_link})

    def get_unsub_link(self):
        args = [self.code, self.make_token()]
        verify_link = reverse("hc-unsubscribe-alerts", args=args)
        return settings.SITE_ROOT + verify_link

    @property
    def transport(self):
        if self.kind == "email":
            return transports.Email(self)
        elif self.kind == "webhook":
            return transports.Webhook(self)
        elif self.kind == "slack":
            return transports.Slack(self)
        elif self.kind == "hipchat":
            return transports.HipChat(self)
        elif self.kind == "pd":
            return transports.PagerDuty(self)
        elif self.kind == "victorops":
            return transports.VictorOps(self)
        elif self.kind == "pushbullet":
            return transports.Pushbullet(self)
        elif self.kind == "po":
            return transports.Pushover(self)
        elif self.kind == "opsgenie":
            return transports.OpsGenie(self)
        elif self.kind == "discord":
            return transports.Discord(self)
        elif self.kind == "telegram":
            return transports.Telegram(self)
        elif self.kind == "sms":
            return transports.Sms(self)
        else:
            raise NotImplementedError("Unknown channel kind: %s" % self.kind)

    def notify(self, check):
        if self.transport.is_noop(check):
            return "no-op"

        n = Notification(owner=check, channel=self)
        n.check_status = check.status
        n.error = "Sending"
        n.save()

        if self.kind == "email":
            error = self.transport.notify(check, n.bounce_url()) or ""
        else:
            error = self.transport.notify(check) or ""

        n.error = error
        n.save()

        return error

    @property
    def po_value(self):
        assert self.kind == "po"
        user_key, prio = self.value.split("|")
        prio = int(prio)

hc/front/models.py
from django.db import models

# Create your models here.

hc/front/forms.py
from django import forms
from django.core.validators import RegexValidator
from hc.front.validators import (CronExpressionValidator, TimezoneValidator,
                                 WebhookValidator)


class NameTagsForm(forms.Form):
    name = forms.CharField(max_length=100, required=False)
    tags = forms.CharField(max_length=500, required=False)

    def clean_tags(self):
        result = []

        for part in self.cleaned_data["tags"].split(" "):
            part = part.strip()
            if part != "":
                result.append(part)

        return " ".join(result)


class TimeoutForm(forms.Form):
    timeout = forms.IntegerField(min_value=60, max_value=2592000)
    grace = forms.IntegerField(min_value=60, max_value=2592000)


class CronForm(forms.Form):
    schedule = forms.CharField(max_length=100,
                               validators=[CronExpressionValidator()])
    tz = forms.CharField(max_length=36, validators=[TimezoneValidator()])
    grace = forms.IntegerField(min_value=1, max_value=43200)


class AddPdForm(forms.Form):
    error_css_class = "has-error"
    value = forms.CharField(max_length=32)


class AddOpsGenieForm(forms.Form):
    error_css_class = "has-error"
    value = forms.CharField(max_length=40)


class AddEmailForm(forms.Form):
    error_css_class = "has-error"
    value = forms.EmailField(max_length=100)


class AddUrlForm(forms.Form):
    error_css_class = "has-error"
    value = forms.URLField(max_length=1000, validators=[WebhookValidator()])


class AddWebhookForm(forms.Form):
    error_css_class = "has-error"

    value_down = forms.URLField(max_length=1000, required=False,
                                validators=[WebhookValidator()])

    value_up = forms.URLField(max_length=1000, required=False,
                              validators=[WebhookValidator()])

    post_data = forms.CharField(max_length=1000, required=False)

    def get_value(self):
        d = self.cleaned_data
        return "\n".join((d["value_down"], d["value_up"], d["post_data"]))


phone_validator = RegexValidator(regex='^\+\d{5,15}$',
                                 message="Invalid phone number format.")


class AddSmsForm(forms.Form):
    error_css_class = "has-error"
    value = forms.CharField(max_length=16, validators=[phone_validator])

templates/front/about.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}About - healthchecks.io{% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <h3>Contact</h3>
        <p>Email: <a href="mailto:contact@healthchecks.io">contact@healthchecks.io</a></p>
        <p>Twitter: <a href="https://twitter.com/healthchecks_io">@healthchecks_io</a></p>
        <p>Mailing address:</p>
        <address>
            <strong>Monkey See Monkey Do SIA</strong><br>
            Gaujas iela 4-2<br>
            Valmiera, LV-4201<br>
            Latvia
        </address>

        <h3>Open Source</h3>
        <p>
            healthchecks.io is an open source project. The code is on
            <a href="https://github.com/healthchecks/healthchecks">GitHub</a>,
            it has BSD license, and is accepting contributions.
        </p>

        <h3>Reliability Guarantees</h3>
        <p>
            The service is currently run on Google Cloud Platform.
            The app servers are load balanced, but the Postgres database
            currently is a single point of failure. The database does have
            daily backups. The ops team consists of a single person, so
            multi-hour or even multi-day outages are possible!
        </p>
        <p>
            While we can only guarantee a <em>best effort</em> availability,
            in practice the availability has exceeded 99.9% since the service
            publicly launched in July 2015. That is, until 20 August 2016,
            when the service <a href="https://medium.com/@healthchecks/outage-postmortem-20-august-2016-204297b9d3dd#.dahxkssp8">experienced a 24 hour outage</a>.
        </p>


        <p>
            There's also a number of alternative cron monitoring services, with
            different feature sets, different reliability guarantees and
            pricing options. If healthchecks.io doesn't seem like a good fit
            for you, why not check them out:

            <a href="https://cronitor.io/">Cronitor.io</a>,
            <a href="https://deadmanssnitch.com/">Dead Man's Snitch</a>,
            <a href="https://github.com/quantopian/coal-mine">Coal Mine</a>,
            <a href="http://www.pushmon.com/">PushMon</a>,
            <a href="https://steward.io">steward.io</a>,
            <a href="https://www.cronalarm.com/">CronAlarm</a>,
            <a href="https://wdt.io/">Watchdog Timer</a>.
        </p>
    </div>
</div>
{% endblock %}

templates/front/channels.html
{% extends "base.html" %}
{% load compress humanize staticfiles hc_extras %}

{% block title %}Integrations - {% site_name %}{% endblock %}


{% block content %}
<div class="row">
{% if messages %}
<div class="col-sm-12">
    {% for message in messages %}
        <p class="alert alert-{{ message.tags }}">{{ message }}</p>
    {% endfor %}
</div>
{% endif %}

<div class="col-sm-12">
    <table class="table channels-table">
        {% if channels %}
        <tr>
            <th>Type</th>
            <th>Value</th>
            <th>Assigned Checks</th>
            <th>Last Notification</th>
            <th></th>
        </tr>
        {% for ch in channels %}
        <tr class="channel-row">
            <td>{{ ch.get_kind_display }}</td>
            <td class="value-cell">
                {% if ch.kind == "email" %}
                    <span class="preposition">to</span>
                    {{ ch.value }}
                    {% if not ch.email_verified %}
                        <span class="channel-unconfirmed">(unconfirmed)</span>
                    {% endif %}
                {% elif ch.kind == "pd" %}
                    <span class="preposition">API key</span>
                    {{ ch.value }}
                {% elif ch.kind == "opsgenie" %}
                    <span class="preposition">API key</span>
                    {{ ch.value }}
                {% elif ch.kind == "victorops" %}
                    <span class="preposition">Post URL</span>
                    {{ ch.value }}
                {% elif ch.kind == "po" %}
                    <span class="preposition">user key</span>
                    {{ ch.po_value|first }}
                    ({{ ch.po_value|last }} priority)
                {% elif ch.kind == "slack" %}
                    {% if ch.slack_team %}
                        <span class="preposition">team</span>
                        {{ ch.slack_team }},
                        <span class="preposition">channel</span>
                        {{ ch.slack_channel }}
                    {% else %}
                        {{ ch.value }}
                    {% endif %}
                {% elif ch.kind == "webhook" %}
                    <table>
                        {% if ch.value_down %}
                        <tr>
                            <td class="preposition">down&nbsp;</td>
                            <td>{{ ch.value_down }}</td>
                        </tr>
                        {% endif %}
                        {% if ch.value_up %}
                        <tr>
                            <td class="preposition">up&nbsp;</td>
                            <td>{{ ch.value_up }}</td>
                        </tr>
                        {% endif %}
                        {% if ch.post_data %}
                        <tr>
                            <td class="preposition">body&nbsp;</td>
                            <td>{{ ch.post_data }}</td>
                        </tr>
                        {% endif %}
                    </table>
                {% elif ch.kind == "pushbullet" %}
                    <span class="preposition">API key</span>
                    {{ ch.value }}
                {% elif ch.kind == "discord" %}
                    {{ ch.discord_webhook_id }}
                {% elif ch.kind == "telegram" %}
                    {% if ch.telegram_type == "group" %}
                    <span class="preposition">chat</span>
                    {% elif ch.telegram_type == "private" %}
                    <span class="preposition">user</span>
                    {% endif %}
                    {{ ch.telegram_name }}
                {% else %}
                    {{ ch.value }}
                {% endif %}
            </td>
            <td class="channels-num-checks">
                <a
                    class="edit-checks"
                    href="{% url 'hc-channel-checks' ch.code %}">
                    {{ ch.n_checks }} of {{ num_checks }}
                </a>
            </td>
            <td>
            {% with n=ch.latest_notification %}
                {% if n %}
                    {% if n.error %}
                    <span class="text-danger" data-toggle="tooltip" title="{{ n.error }}">
                        <strong>Failed</strong>, {{ n.created|naturaltime }}
                    </span>
                    {% else %}
                    Delivered, {{ n.created|naturaltime }}
                    {% endif %}
                {% else %}
                Never
                {% endif %}
                {% if ch.kind == "sms" %}
                    <p>Used {{ profile.sms_sent_this_month }} of {{ profile.sms_limit }} sends this month.</p>
                {% endif %}
            {% endwith %}
            </td>
            <td>
                <button
                    data-kind="{{ ch.get_kind_display }}"
                    data-url="{% url 'hc-remove-channel' ch.code %}"
                    class="btn btn-sm btn-default channel-remove"
                    type="button">
                    <span class="icon-delete"></span>
                </button>
            </td>
            <td>

            </td>
        </tr>
        {% endfor %}
        {% endif %}
    </table>


    <h1 class="ai-title">Add More</h1>
    <ul class="add-integration">
        <li>
            <img src="{% static 'img/integrations/slack.png' %}"
                class="icon" alt="Slack icon" />

            <h2>Slack</h2>
            <p>A messaging app for teams.</p>
            <a href="{% url 'hc-add-slack' %}" class="btn btn-primary">Add Integration</a>
        </li>
        <li>
            <img src="{% static 'img/integrations/email.png' %}"
                class="icon" alt="Email icon" />

            <h2>Email</h2>
            <p>Get an email message when a check goes up or down.</p>

            <a href="{% url 'hc-add-email' %}" class="btn btn-primary">Add Integration</a>
        </li>
        {% if enable_sms %}
        <li>
            <img src="{% static 'img/integrations/sms.png' %}"
                class="icon" alt="SMS icon" />

            <h2>SMS {% if show_pricing %}<small>(paid plans)</small>{% endif %}</h2>
            <p>Get a text message to your phone when a check goes down.</p>

            <a href="{% url 'hc-add-sms' %}" class="btn btn-primary">Add Integration</a>
        </li>
        {% endif %}
        <li>
            <img src="{% static 'img/integrations/webhook.png' %}"
                class="icon" alt="Webhook icon" />

            <h2>Webhook</h2>
            <p>Receive a HTTP callback when a check goes down.</p>

            <a href="{% url 'hc-add-webhook' %}" class="btn btn-primary">Add Integration</a>
        </li>
        {% if enable_pushover %}
        <li>
            <img src="{% static 'img/integrations/pushover.png' %}"
                 class="icon" alt="Pushover icon" />

            <h2>Pushover</h2>
            <p>Receive instant push notifications on your phone or tablet.</p>

            <a href="{% url 'hc-add-pushover' %}" class="btn btn-primary">Add Integration</a>
        </li>
        {% endif %}
        {% if enable_pushbullet %}
        <li>
            <img src="{% static 'img/integrations/pushbullet.png' %}"
                 class="icon" alt="Pushbullet icon" />

            <h2>Pushbullet</h2>
            <p>Pushbullet connects your devices, making them feel like one.</p>

            <a href="{% url 'hc-add-pushbullet' %}" class="btn btn-primary">Add Integration</a>
        </li>
        {% endif %}
        {% if enable_telegram %}
        <li>
            <img src="{% static 'img/integrations/telegram.png' %}"
                 class="icon" alt="Telegram icon" />

            <h2>Telegram</h2>
            <p>A messaging app with a focus on speed and security.</p>

            <a href="{% url 'hc-add-telegram' %}" class="btn btn-primary">Add Integration</a>
        </li>
        {% endif %}
        <li>
            <img src="{% static 'img/integrations/pd.png' %}"
                class="icon" alt="PagerDuty icon" />

            <h2>PagerDuty</h2>
            <p>On-call scheduling, alerting, and incident tracking.</p>

            <a href="{% url 'hc-add-pd' %}" class="btn btn-primary">Add Integration</a>
        </li>
        <li>
            <img src="{% static 'img/integrations/hipchat.png' %}"
                class="icon" alt="HipChat icon" />

            <h2>HipChat</h2>
            <p>Group and private chat, file sharing, and integrations.</p>

            <a href="{% url 'hc-add-hipchat' %}" class="btn btn-primary">Add Integration</a>
        </li>
        <li>
            <img src="{% static 'img/integrations/victorops.png' %}"
                class="icon" alt="VictorOps icon" />

            <h2>VictorOps</h2>
            <p>On-call scheduling, alerting, and incident tracking.</p>

            <a href="{% url 'hc-add-victorops' %}" class="btn btn-primary">Add Integration</a>
        </li>
        {% if enable_discord %}
        <li>
            <img src="{% static 'img/integrations/discord.png' %}"
                 class="icon" alt="Discord icon" />

            <h2>Discord</h2>
            <p>Cross-platform voice and text chat app designed for gamers.</p>

            <a href="{% url 'hc-add-discord' %}" class="btn btn-primary">Add Integration</a>
        </li>
        {% endif %}
        <li>
            <img src="{% static 'img/integrations/opsgenie.png' %}"
                class="icon" alt="OpsGenie icon" />

            <h2>OpsGenie</h2>
            <p> Alerting &amp; Incident Management Solution for Dev &amp; Ops.</p>

            <a href="{% url 'hc-add-opsgenie' %}" class="btn btn-primary">Add Integration</a>
        </li>
        <li class="link-to-github">
            <img src="{% static 'img/integrations/missing.png' %}"
                 class="icon" alt="Suggest New Integration" />
            <p>
                Your favorite service or notification method not listed? <br />
                Please <a href="https://github.com/healthchecks/healthchecks/issues">file an issue on GitHub</a>!
            </p>
        </li>

    </ul>
</div>
</div>

<div id="checks-modal" class="modal">
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>

<div id="remove-channel-modal" class="modal">
    <div class="modal-dialog">
        <form id="remove-channel-form" method="post">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="remove-check-title">
                        Remove this
                        <span class="remove-channel-kind">---</span>
                        Integration?
                    </h4>
                </div>
                <div class="modal-body">
                    <p>You are about to remove this
                        <span class="remove-channel-kind">---</span>
                    integration.
                    </p>
                    <p>Once it's gone it's gone. But, if you change your
                    mind later, you can create a similar channel again.
                    Do you want to continue?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-danger">Remove</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

{% block scripts %}
{% compress js %}
<script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/channels.js' %}"></script>
{% endcompress %}
{% endblock %}

templates/front/cron_preview.html
{% load humanize tz %}

{% if bad_schedule %}
<p id="invalid-arguments">
    Invalid cron expression. <br />
    Please check the <a href="{% url 'hc-docs-cron' %}">supported cron syntax features</a>.

</p>
{% elif bad_tz %}
<p id="invalid-arguments">Invalid timezone</p>
{% else %}
<table id="cron-preview-table" class="table">
    <tr><th id="cron-preview-title" colspan="3">Expected Ping Dates</th></tr>
    {% for naive, aware in dates %}
    <tr>
        <td>{{ naive|date:"M j, H:i" }}</td>
        <td>{{ aware|naturaltime }}</td>
        <td class="hidden-xs">{{ aware|date:"c" }}</td>
    </tr>
    {% endfor %}
</table>
{% endif %}